server:
  port: 8081

spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/tcc_order?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: bigdata
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 10
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: db
      started: true
      hmilyDbConfig:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/tcc?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
        username: bigdata
        password: 123456


